/**
 * useHandGesture
 *
 * Detects palm position via webcam using MediaPipe HandLandmarker.
 * Applies a dead zone and outputs a rotation delta via `deltaRef`
 * (a MutableRefObject, not state) so the animation loop can read it
 * each frame without triggering React re-renders.
 *
 * Assets must be pre-generated by:  node scripts/setup-mediapipe.mjs
 */

import { useCallback, useEffect, useRef, useState } from 'react';
import { HandLandmarker, FilesetResolver } from '@mediapipe/tasks-vision';

// --- Constants ---
const WASM_PATH = '/mediapipe';
const MODEL_PATH = '/models/hand_landmarker.task';

// Palm center = average of wrist (0) + four finger MCP joints (5, 9, 13, 17)
const PALM_INDICES = [0, 5, 9, 13, 17] as const;

// --- Types ---
export interface GestureDelta {
  x: number; // positive → user hand visually right
  y: number; // positive → user hand visually up
}

interface UseHandGestureOptions {
  /** Dead zone as a fraction of half-screen (default 0.12) */
  deadZone?: number;
}

// --- Hook ---
export function useHandGesture({ deadZone = 0.12 }: UseHandGestureOptions = {}) {
  const [isModelReady, setIsModelReady] = useState(false);
  const [isEnabled, setIsEnabled] = useState(false);
  const [isActive, setIsActive] = useState(false);
  const [hasError, setHasError] = useState(false);
  const [palmPos, setPalmPos] = useState<{ x: number; y: number } | null>(null);

  const videoRef = useRef<HTMLVideoElement>(null);
  const landmarkerRef = useRef<HandLandmarker | null>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const rafRef = useRef<number>(0);
  const deltaRef = useRef<GestureDelta>({ x: 0, y: 0 });
  const deadZoneRef = useRef(deadZone);

  // Keep dead zone ref in sync without restarting the camera
  useEffect(() => {
    deadZoneRef.current = deadZone;
  }, [deadZone]);

  // --- Effect 1: Initialize MediaPipe HandLandmarker (once on mount) ---
  useEffect(() => {
    let cancelled = false;

    (async () => {
      try {
        const vision = await FilesetResolver.forVisionTasks(WASM_PATH);

        let landmarker: HandLandmarker;
        try {
          // Prefer GPU delegate for performance
          landmarker = await HandLandmarker.createFromOptions(vision, {
            baseOptions: { modelAssetPath: MODEL_PATH, delegate: 'GPU' },
            runningMode: 'VIDEO',
            numHands: 1,
          });
        } catch {
          // Fall back to CPU if GPU is unavailable
          landmarker = await HandLandmarker.createFromOptions(vision, {
            baseOptions: { modelAssetPath: MODEL_PATH, delegate: 'CPU' },
            runningMode: 'VIDEO',
            numHands: 1,
          });
        }

        if (!cancelled) {
          landmarkerRef.current = landmarker;
          setIsModelReady(true);
        }
      } catch {
        if (!cancelled) setHasError(true);
      }
    })();

    return () => {
      cancelled = true;
      landmarkerRef.current?.close();
    };
  }, []);

  // --- Effect 2: Webcam + detection loop (runs when enabled & model ready) ---
  useEffect(() => {
    if (!isEnabled || !isModelReady) return;

    let active = true;

    (async () => {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({
          video: { width: 640, height: 480, facingMode: 'user' },
        });

        if (!active) {
          stream.getTracks().forEach((t) => t.stop());
          return;
        }

        streamRef.current = stream;

        // Attach stream after getUserMedia resolves (DOM is guaranteed ready by then)
        const video = videoRef.current;
        if (!video) {
          stream.getTracks().forEach((t) => t.stop());
          return;
        }

        video.srcObject = stream;
        await video.play();
        if (!active) return;

        setIsActive(true);

        // rAF-based detection loop
        const detect = () => {
          if (!active || !landmarkerRef.current) return;

          const result = landmarkerRef.current.detectForVideo(video, performance.now());

          if (result.landmarks.length > 0) {
            const lm = result.landmarks[0];

            // Compute palm center from wrist + finger MCP joints
            const px = PALM_INDICES.reduce((s, i) => s + lm[i].x, 0) / PALM_INDICES.length;
            const py = PALM_INDICES.reduce((s, i) => s + lm[i].y, 0) / PALM_INDICES.length;

            setPalmPos({ x: px, y: py });

            // Apply dead zone and produce directional delta
            // Front camera raw image: user's physical right → low x (camera left = user right)
            // So: negate x offset to align with user's visual perception
            const dz = deadZoneRef.current;
            const applyDZ = (v: number) => {
              const a = Math.abs(v);
              return a < dz ? 0 : Math.sign(v) * ((a - dz) / (0.5 - dz));
            };

            deltaRef.current = {
              x: -applyDZ(px - 0.5), // positive = user's hand visually right
              y: -applyDZ(py - 0.5), // positive = user's hand visually up (raw y inverted)
            };
          } else {
            setPalmPos(null);
            deltaRef.current = { x: 0, y: 0 };
          }

          rafRef.current = requestAnimationFrame(detect);
        };

        rafRef.current = requestAnimationFrame(detect);
      } catch {
        if (active) setHasError(true);
      }
    })();

    return () => {
      active = false;
      cancelAnimationFrame(rafRef.current);
      streamRef.current?.getTracks().forEach((t) => t.stop());
      streamRef.current = null;
      setPalmPos(null);
      deltaRef.current = { x: 0, y: 0 };
      setIsActive(false);
    };
  }, [isEnabled, isModelReady]);

  const toggle = useCallback(() => {
    if (hasError) return;
    setIsEnabled((v) => !v);
  }, [hasError]);

  return {
    isModelReady,
    isEnabled,
    isActive,
    hasError,
    toggle,
    videoRef,
    palmPos,
    deltaRef,
    deadZone,
  };
}
